package com.realswordteam.asdust.items;

import com.realswordteam.asdust.ASDUST;
import com.realswordteam.asdust.items.itembase.ItemChemicalElementBase;
import net.minecraft.item.Item;

public class ItemChemicalElementRegistry {
    public static Item ELEMENT_001_H = null;
    public static Item ELEMENT_002_He = null;
    public static Item ELEMENT_003_Li = null;
    public static Item ELEMENT_004_Be = null;
    public static Item ELEMENT_005_B = null;
    public static Item ELEMENT_006_C = null;
    public static Item ELEMENT_007_N = null;
    public static Item ELEMENT_008_O = null;
    public static Item ELEMENT_009_F = null;
    public static Item ELEMENT_010_Ne = null;
    public static Item ELEMENT_011_Na = null;
    public static Item ELEMENT_012_Mg = null;
    public static Item ELEMENT_013_Al = null;
    public static Item ELEMENT_014_Si = null;
    public static Item ELEMENT_015_P = null;
    public static Item ELEMENT_016_S = null;
    public static Item ELEMENT_017_Cl = null;
    public static Item ELEMENT_018_Ar = null;
    public static Item ELEMENT_019_K = null;
    public static Item ELEMENT_020_Ca = null;
    public static Item ELEMENT_021_Sc = null;
    public static Item ELEMENT_022_Ti = null;
    public static Item ELEMENT_023_V = null;
    public static Item ELEMENT_024_Cr = null;
    public static Item ELEMENT_025_Mn = null;
    public static Item ELEMENT_026_Fe = null;
    public static Item ELEMENT_027_Co = null;
    public static Item ELEMENT_028_Ni = null;
    public static Item ELEMENT_029_Cu = null;
    public static Item ELEMENT_030_Zn = null;
    public static Item ELEMENT_031_Ga = null;
    public static Item ELEMENT_032_Ge = null;
    public static Item ELEMENT_033_As = null;
    public static Item ELEMENT_034_Se = null;
    public static Item ELEMENT_035_Br = null;
    public static Item ELEMENT_036_Kr = null;
    public static Item ELEMENT_037_Rb = null;
    public static Item ELEMENT_038_Sr = null;
    public static Item ELEMENT_039_Y = null;
    public static Item ELEMENT_040_Zr = null;
    public static Item ELEMENT_041_Nb = null;
    public static Item ELEMENT_042_Mo = null;
    public static Item ELEMENT_043_Tc = null;
    public static Item ELEMENT_044_Ru = null;
    public static Item ELEMENT_045_Rh = null;
    public static Item ELEMENT_046_Pd = null;
    public static Item ELEMENT_047_Ag = null;
    public static Item ELEMENT_048_Cd = null;
    public static Item ELEMENT_049_In = null;
    public static Item ELEMENT_050_Sn = null;
    public static Item ELEMENT_051_Sb = null;
    public static Item ELEMENT_052_Te = null;
    public static Item ELEMENT_053_I = null;
    public static Item ELEMENT_054_Xe = null;
    public static Item ELEMENT_055_Cs = null;
    public static Item ELEMENT_056_Ba = null;
    public static Item ELEMENT_057_La = null;
    public static Item ELEMENT_058_Ce = null;
    public static Item ELEMENT_059_Pr = null;
    public static Item ELEMENT_060_Nd = null;
    public static Item ELEMENT_061_Pm = null;
    public static Item ELEMENT_062_Sm = null;
    public static Item ELEMENT_063_Eu = null;
    public static Item ELEMENT_064_Gd = null;
    public static Item ELEMENT_065_Tb = null;
    public static Item ELEMENT_066_Dy = null;
    public static Item ELEMENT_067_Ho = null;
    public static Item ELEMENT_068_Er = null;
    public static Item ELEMENT_069_Tm = null;
    public static Item ELEMENT_070_Yb = null;
    public static Item ELEMENT_071_Lu = null;
    public static Item ELEMENT_072_Hf = null;
    public static Item ELEMENT_073_Ta = null;
    public static Item ELEMENT_074_W = null;
    public static Item ELEMENT_075_Re = null;
    public static Item ELEMENT_076_Os = null;
    public static Item ELEMENT_077_Ir = null;
    public static Item ELEMENT_078_Pt = null;
    public static Item ELEMENT_079_Au = null;
    public static Item ELEMENT_080_Hg = null;
    public static Item ELEMENT_081_Tl = null;
    public static Item ELEMENT_082_Pb = null;
    public static Item ELEMENT_083_Bi = null;
    public static Item ELEMENT_084_Po = null;
    public static Item ELEMENT_085_At = null;
    public static Item ELEMENT_086_Rn = null;
    public static Item ELEMENT_087_Fr = null;
    public static Item ELEMENT_088_Ra = null;
    public static Item ELEMENT_089_Ac = null;
    public static Item ELEMENT_090_Th = null;
    public static Item ELEMENT_091_Pa = null;
    public static Item ELEMENT_092_U = null;
    public static Item ELEMENT_093_Np = null;
    public static Item ELEMENT_094_Pu = null;
    public static Item ELEMENT_095_Am = null;
    public static Item ELEMENT_096_Cm = null;
    public static Item ELEMENT_097_Bk = null;
    public static Item ELEMENT_098_Cf = null;
    public static Item ELEMENT_099_Es = null;
    public static Item ELEMENT_100_Fm = null;
    public static Item ELEMENT_101_Md = null;
    public static Item ELEMENT_102_No = null;
    public static Item ELEMENT_103_Lr = null;
    public static Item ELEMENT_104_Rf = null;

    public static Item[] chemicalElements =
            {
                    setItemName(ELEMENT_001_H = new ItemChemicalElementBase(), "element_001_h"),
                    setItemName(ELEMENT_002_He = new ItemChemicalElementBase(), "element_002_he"),
                    setItemName(ELEMENT_003_Li = new ItemChemicalElementBase(), "element_003_li"),
                    setItemName(ELEMENT_004_Be = new ItemChemicalElementBase(), "element_004_be"),
                    setItemName(ELEMENT_005_B = new ItemChemicalElementBase(), "element_005_b"),
                    setItemName(ELEMENT_006_C = new ItemChemicalElementBase(), "element_006_c"),
                    setItemName(ELEMENT_007_N = new ItemChemicalElementBase(), "element_007_n"),
                    setItemName(ELEMENT_008_O = new ItemChemicalElementBase(), "element_008_o"),
                    setItemName(ELEMENT_009_F = new ItemChemicalElementBase(), "element_009_f"),
                    setItemName(ELEMENT_010_Ne = new ItemChemicalElementBase(), "element_010_ne"),
                    setItemName(ELEMENT_011_Na = new ItemChemicalElementBase(), "element_011_na"),
                    setItemName(ELEMENT_012_Mg = new ItemChemicalElementBase(), "element_012_mg"),
                    setItemName(ELEMENT_013_Al = new ItemChemicalElementBase(), "element_013_al"),
                    setItemName(ELEMENT_014_Si = new ItemChemicalElementBase(), "element_014_si"),
                    setItemName(ELEMENT_015_P = new ItemChemicalElementBase(), "element_015_p"),
                    setItemName(ELEMENT_016_S = new ItemChemicalElementBase(), "element_016_s"),
                    setItemName(ELEMENT_017_Cl = new ItemChemicalElementBase(), "element_017_cl"),
                    setItemName(ELEMENT_018_Ar = new ItemChemicalElementBase(), "element_018_ar"),
                    setItemName(ELEMENT_019_K = new ItemChemicalElementBase(), "element_019_k"),
                    setItemName(ELEMENT_020_Ca = new ItemChemicalElementBase(), "element_020_ca"),
                    setItemName(ELEMENT_021_Sc = new ItemChemicalElementBase(), "element_021_sc"),
                    setItemName(ELEMENT_022_Ti = new ItemChemicalElementBase(), "element_022_ti"),
                    setItemName(ELEMENT_023_V = new ItemChemicalElementBase(), "element_023_v"),
                    setItemName(ELEMENT_024_Cr = new ItemChemicalElementBase(), "element_024_cr"),
                    setItemName(ELEMENT_025_Mn = new ItemChemicalElementBase(), "element_025_mn"),
                    setItemName(ELEMENT_026_Fe = new ItemChemicalElementBase(), "element_026_fe"),
                    setItemName(ELEMENT_027_Co = new ItemChemicalElementBase(), "element_027_co"),
                    setItemName(ELEMENT_028_Ni = new ItemChemicalElementBase(), "element_028_ni"),
                    setItemName(ELEMENT_029_Cu = new ItemChemicalElementBase(), "element_029_cu"),
                    setItemName(ELEMENT_030_Zn = new ItemChemicalElementBase(), "element_030_zn"),
                    setItemName(ELEMENT_031_Ga = new ItemChemicalElementBase(), "element_031_ga"),
                    setItemName(ELEMENT_032_Ge = new ItemChemicalElementBase(), "element_032_ge"),
                    setItemName(ELEMENT_033_As = new ItemChemicalElementBase(), "element_033_as"),
                    setItemName(ELEMENT_034_Se = new ItemChemicalElementBase(), "element_034_se"),
                    setItemName(ELEMENT_035_Br = new ItemChemicalElementBase(), "element_035_br"),
                    setItemName(ELEMENT_036_Kr = new ItemChemicalElementBase(), "element_036_kr"),
                    setItemName(ELEMENT_037_Rb = new ItemChemicalElementBase(), "element_037_rb"),
                    setItemName(ELEMENT_038_Sr = new ItemChemicalElementBase(), "element_038_sr"),
                    setItemName(ELEMENT_039_Y = new ItemChemicalElementBase(), "element_039_y"),
                    setItemName(ELEMENT_040_Zr = new ItemChemicalElementBase(), "element_040_zr"),
                    setItemName(ELEMENT_041_Nb = new ItemChemicalElementBase(), "element_041_nb"),
                    setItemName(ELEMENT_042_Mo = new ItemChemicalElementBase(), "element_042_mo"),
                    setItemName(ELEMENT_043_Tc = new ItemChemicalElementBase(), "element_043_tc"),
                    setItemName(ELEMENT_044_Ru = new ItemChemicalElementBase(), "element_044_ru"),
                    setItemName(ELEMENT_045_Rh = new ItemChemicalElementBase(), "element_045_rh"),
                    setItemName(ELEMENT_046_Pd = new ItemChemicalElementBase(), "element_046_pd"),
                    setItemName(ELEMENT_047_Ag = new ItemChemicalElementBase(), "element_047_ag"),
                    setItemName(ELEMENT_048_Cd = new ItemChemicalElementBase(), "element_048_cd"),
                    setItemName(ELEMENT_049_In = new ItemChemicalElementBase(), "element_049_in"),
                    setItemName(ELEMENT_050_Sn = new ItemChemicalElementBase(), "element_050_sn"),
                    setItemName(ELEMENT_051_Sb = new ItemChemicalElementBase(), "element_051_sb"),
                    setItemName(ELEMENT_052_Te = new ItemChemicalElementBase(), "element_052_te"),
                    setItemName(ELEMENT_053_I = new ItemChemicalElementBase(), "element_053_i"),
                    setItemName(ELEMENT_054_Xe = new ItemChemicalElementBase(), "element_054_xe"),
                    setItemName(ELEMENT_055_Cs = new ItemChemicalElementBase(), "element_055_cs"),
                    setItemName(ELEMENT_056_Ba = new ItemChemicalElementBase(), "element_056_ba"),
                    setItemName(ELEMENT_057_La = new ItemChemicalElementBase(), "element_057_la"),
                    setItemName(ELEMENT_058_Ce = new ItemChemicalElementBase(), "element_058_ce"),
                    setItemName(ELEMENT_059_Pr = new ItemChemicalElementBase(), "element_059_pr"),
                    setItemName(ELEMENT_060_Nd = new ItemChemicalElementBase(), "element_060_nd"),
                    setItemName(ELEMENT_061_Pm = new ItemChemicalElementBase(), "element_061_pm"),
                    setItemName(ELEMENT_062_Sm = new ItemChemicalElementBase(), "element_062_sm"),
                    setItemName(ELEMENT_063_Eu = new ItemChemicalElementBase(), "element_063_eu"),
                    setItemName(ELEMENT_064_Gd = new ItemChemicalElementBase(), "element_064_gd"),
                    setItemName(ELEMENT_065_Tb = new ItemChemicalElementBase(), "element_065_tb"),
                    setItemName(ELEMENT_066_Dy = new ItemChemicalElementBase(), "element_066_dy"),
                    setItemName(ELEMENT_067_Ho = new ItemChemicalElementBase(), "element_067_ho"),
                    setItemName(ELEMENT_068_Er = new ItemChemicalElementBase(), "element_068_er"),
                    setItemName(ELEMENT_069_Tm = new ItemChemicalElementBase(), "element_069_tm"),
                    setItemName(ELEMENT_070_Yb = new ItemChemicalElementBase(), "element_070_yb"),
                    setItemName(ELEMENT_071_Lu = new ItemChemicalElementBase(), "element_071_lu"),
                    setItemName(ELEMENT_072_Hf = new ItemChemicalElementBase(), "element_072_hf"),
                    setItemName(ELEMENT_073_Ta = new ItemChemicalElementBase(), "element_073_ta"),
                    setItemName(ELEMENT_074_W = new ItemChemicalElementBase(), "element_074_w"),
                    setItemName(ELEMENT_075_Re = new ItemChemicalElementBase(), "element_075_re"),
                    setItemName(ELEMENT_076_Os = new ItemChemicalElementBase(), "element_076_os"),
                    setItemName(ELEMENT_077_Ir = new ItemChemicalElementBase(), "element_077_ir"),
                    setItemName(ELEMENT_078_Pt = new ItemChemicalElementBase(), "element_078_pt"),
                    setItemName(ELEMENT_079_Au = new ItemChemicalElementBase(), "element_079_au"),
                    setItemName(ELEMENT_080_Hg = new ItemChemicalElementBase(), "element_080_hg"),
                    setItemName(ELEMENT_081_Tl = new ItemChemicalElementBase(), "element_081_tl"),
                    setItemName(ELEMENT_082_Pb = new ItemChemicalElementBase(), "element_082_pb"),
                    setItemName(ELEMENT_083_Bi = new ItemChemicalElementBase(), "element_083_bi"),
                    setItemName(ELEMENT_084_Po = new ItemChemicalElementBase(), "element_084_po"),
                    setItemName(ELEMENT_085_At = new ItemChemicalElementBase(), "element_085_at"),
                    setItemName(ELEMENT_086_Rn = new ItemChemicalElementBase(), "element_086_rn"),
                    setItemName(ELEMENT_087_Fr = new ItemChemicalElementBase(), "element_087_fr"),
                    setItemName(ELEMENT_088_Ra = new ItemChemicalElementBase(), "element_088_ra"),
                    setItemName(ELEMENT_089_Ac = new ItemChemicalElementBase(), "element_089_ac"),
                    setItemName(ELEMENT_090_Th = new ItemChemicalElementBase(), "element_090_th"),
                    setItemName(ELEMENT_091_Pa = new ItemChemicalElementBase(), "element_091_pa"),
                    setItemName(ELEMENT_092_U = new ItemChemicalElementBase(), "element_092_u"),
                    setItemName(ELEMENT_093_Np = new ItemChemicalElementBase(), "element_093_np"),
                    setItemName(ELEMENT_094_Pu = new ItemChemicalElementBase(), "element_094_pu"),
                    setItemName(ELEMENT_095_Am = new ItemChemicalElementBase(), "element_095_am"),
                    setItemName(ELEMENT_096_Cm = new ItemChemicalElementBase(), "element_096_cm"),
                    setItemName(ELEMENT_097_Bk = new ItemChemicalElementBase(), "element_097_bk"),
                    setItemName(ELEMENT_098_Cf = new ItemChemicalElementBase(), "element_098_cf"),
                    setItemName(ELEMENT_099_Es = new ItemChemicalElementBase(), "element_099_es"),
                    setItemName(ELEMENT_100_Fm = new ItemChemicalElementBase(), "element_100_fm"),
                    setItemName(ELEMENT_101_Md = new ItemChemicalElementBase(), "element_101_md"),
                    setItemName(ELEMENT_102_No = new ItemChemicalElementBase(), "element_102_no"),
                    setItemName(ELEMENT_103_Lr = new ItemChemicalElementBase(), "element_103_lr"),
                    setItemName(ELEMENT_104_Rf = new ItemChemicalElementBase(), "element_104_rf"),
            };

    private static Item setItemName(Item item, String name)
    {
        return item.setRegistryName(ASDUST.MODID,name).setUnlocalizedName(ASDUST.MODID + "." + name);
    }
}
